### ISSUE TITLE
python3.6 initialize.py -3 SF1 TF1 16000,     FileNotFoundError: [Errno 2] No such file or directory: 'data/wav/.wav'

### ISSUE THREAD

**Issue by vayusutha** [k2kobayashi/sprocket#126]
I was able to run example upto initialize configure files for the source and target speakers and the speaker-pair.
But when i try to trace f0,   i,e python initialize.py -3 SF1 TF1 16000,  im getting trace back error as follows:

Traceback (most recent call last):
  File "initialize.py", line 180, in <module>
    str(WAV_DIR), str(CONF_DIR / "figure"))
  File "/media/vayu/01D38AA42152F1F0/sprocket/sprocket-master/example/src/initialize_speaker.py", line 87, in main
    fs, x = wavfile.read(wavf)
  File "/home/vayu/.local/lib/python3.6/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/wav/.wav'

Please help me to debug it...

**Comment by astridreadygo** [comment]
Sorry but I met with the same problem. I was wondering if you could explain how you debug to fix this? I have tried to reach out the "initialize_speaker.py" and tried to use "f = f.strip()" in line 85 instead of "f = f.rstrip()", but it was still not working.

**Comment by astridreadygo** [comment]
Thanks but I have checked that out on my own. When using nano to edit the SF1_test.list file, there is an extra blank line after the last "SF1/100030". Simply withdraw the Enter key from the next line to "SF1/100030" in SF1_test.list file. I found this since the code is not processing after it extracts the SF1/100030.wav which happened to be the end of SF1 folder.
